name: Send Data to API

on:
  push:
    branches:
      - main

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send name and student ID to API
      run: |
        curl -X POST https://shams.sython.ir/test.php \
          -H "Content-Type: application/json" \
          -d '{"name": "AmirHosseinNorozi", "studentid": "01131033907039"}'
