name: Send Data and Save Token

on:
  push:
    branches:
      - main

jobs:
  send-request-and-save-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send name and student ID to API and get token
      id: request
      run: |
        # Send POST request and capture the response
        response=$(curl -X POST https://shams.sython.ir/test.php \
          -H "Content-Type: application/json" \
          -d '{"name": "ParsaMaghsodian", "studentid": "01130033907029"}')
        
        # Extract token from the response (assuming the token is in JSON format like: {"token": "df40684cbb0f409d0f97614db1518985"})
        token=$(echo "$response" | jq -r '.token')

        # Save token to a file
        echo "$token" > token.txt

    - name: Commit token to the repository
      run: |
        git config --global user.email "parsa.maghsodian@gmail.com"
        git config --global user.name "ParsaMaghsodian"
        
        # Add and commit the token file
        git add token.txt
        git commit -m "Add token file"
        git push
